test

diff --git a/.github/workflows/build-openwrt-r68s.yml b/.github/workflows/build-openwrt-r68s.yml
--- a/.github/workflows/build-openwrt-r68s.yml
+++ b/.github/workflows/build-openwrt-r68s.yml
@@ -30,11 +30,14 @@ env:
 
 jobs:
   build:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
     if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
+
     steps:
       - name: Checkout
-        uses: actions/checkout@v5
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
 
       - name: Initialization environment
         id: init
@@ -61,7 +64,7 @@ jobs:
           sudo -E timedatectl set-ntp true
           date -u
           timedatectl status || true
-          echo "status=success" >> ${{ github.output }}
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Create simulated physical disk
         run: |
@@ -79,40 +82,40 @@ jobs:
           sudo mkdir -p /builder
           sudo mount /dev/github/runner /builder
           sudo chown -R runner:runner /builder
-          # Prepare cached directory
-          echo "Preparing cached directory..."
-          sudo cp -af /home/runner/actions-runner/cached /builder/cached
-          rm -rf /home/runner/actions-runner/cached
-          sudo ln -sf /builder/cached /home/runner/actions-runner/cached
-          echo "_diag directory content:"
-          ls -lh /home/runner/actions-runner/cached/_diag/ 2>/dev/null
-          echo "Verifying the symbolic link..."
-          ls -ld /home/runner/actions-runner/cached
-          df -Th /home/runner/actions-runner/cached
-          echo "Server disk layout:"
           df -Th
-          echo "status=success" >> ${{ github.output }}
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Clone source code
         id: codes
-        working-directory: /workdir
+        working-directory: /builder
         if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          df -hT $PWD
-          git clone -q --single-branch --depth=1 -b ${REPO_BRANCH} ${REPO_URL} openwrt
-          ln -sf /workdir/openwrt ${{ github.workspace }}/openwrt
-          cd openwrt
-          useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
-          echo "useVersionInfo=$useVersionInfo" >> ${{ github.env }}
-          echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> ${{ github.env }}
-          echo "DATE1=$(date "+%Y-%m-%d")" >> ${{ github.env }}
-          echo "status=success" >> ${{ github.output }}
+          REPO_URL="https://github.com/coolsnowwolf/lede"
+          REPO_NAME="lede"
+          REPO_BRANCH="msater"
+          # Clone source code
+          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
+          ln -sf /builder/openwrt ${{ github.workspace }}/openwrt
+          ln -sf /builder/openwrt /home/runner/work/_actions/ophub/amlogic-s9xxx-openwrt/main/openwrt
+
+          # Create ccache directory
+          mkdir -p ccache
+          ln -sf /builder/ccache ${{ github.workspace }}/openwrt/.ccache
+
+          # Set output information
+          echo "build_tag=OpenWrt_${{ inputs.source_branch }}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_ENV}
+          echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nREPO_NAME: [ ${REPO_NAME} ]"
+          df -hT ${PWD}
+          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
+          echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
+          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Load custom feeds
         run: |
-          [ -e ${FEEDS_CONF} ] && mv ${FEEDS_CONF} openwrt/feeds.conf.default
+          [[ -f "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
           chmod +x ${DIY_P1_SH}
-          cd openwrt
+          cd openwrt/
           ${{ github.workspace }}/${DIY_P1_SH}
 
       - name: Update feeds
@@ -123,90 +126,133 @@ jobs:
 
       - name: Load custom configuration
         run: |
-          [ -e files ] && mv files openwrt/files
-          [ -e ${CONFIG_FILE} ] && mv ${CONFIG_FILE} openwrt/.config
+          [[ -d "files" ]] && mv -f files openwrt/files
+          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
           chmod +x ${DIY_P2_SH}
-          cd openwrt
+          cd openwrt/
           ${{ github.workspace }}/${DIY_P2_SH}
 
       - name: Download package
         id: package
         run: |
-          cd openwrt
+          cd openwrt/
           make defconfig
           make download -j8
           find dl -size -1024c -exec ls -l {} \;
           find dl -size -1024c -exec rm -f {} \;
 
-      - name: Compile the firmware
+      - name: Get OpenWrt source hash
+        id: openwrthash
+        if: ${{ steps.pull.outputs.status }} == 'success' && !cancelled()
+        run: |
+          # Get the latest source hash from the kernel repository
+          repo_path="$(echo "${{ env.REPO_URL }}" | awk -F"github.com/" '{print $2}')"
+          api_url="https://api.github.com/repos/${repo_path}/git/ref/heads/${{ env.REPO_BRANCH }}"
+          source_hash=$(curl -fsSL -m 20 \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              ${api_url} |
+              jq -r '.object.sha'
+          )
+          [[ -z "${source_hash}" || "${source_hash}" == "null" ]] && source_hash="${{ github.sha }}"
+          echo "source_hash=${source_hash}" >> ${GITHUB_ENV}
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Cache ccache
+        uses: actions/cache@v4
+        with:
+          path: /builder/ccache
+          key: openwrt-${{ env.REPO_NAME }}-${{ env.source_hash }}
+          restore-keys: |
+            openwrt-${{ env.REPO_NAME }}-
+
+      - name: Compile the OpenWrt
         id: compile
         run: |
-          cd openwrt
-          echo -e "$(nproc) thread compile"
-          make -j$(nproc) || make -j1 || make -j1 V=s
-          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> ${{ github.env }}
-          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> ${{ github.env }}
-          echo "status=success" >> ${{ github.output }}
-
-      - name: Clean up server space
-        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        run: |
           cd openwrt/
-          rm -rf $(ls . | grep -v "^bin$" | xargs) 2>/dev/null
-          df -hT ${PWD}
-          echo "status=success" >> ${{ github.output }}
+          echo -e "$(nproc) thread compile"
+          make -j$(($(nproc) + 1)) V=s || make -j1 || make -j1 V=s
 
-      - name: Upload bin directory
-        uses: actions/upload-artifact@v4
-        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled() && ${{ env.UPLOAD_BIN_DIR }} == 'true'
-        with:
-          name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-          path: openwrt/bin
+          echo -e "ccache statistics:"
+          ccache -s 2>/dev/null
 
-      - name: Organize files
-        id: organize
-        if: ${{ env.UPLOAD_FIRMWARE }} == 'true' && ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        run: |
-          cd openwrt/bin/targets/*/*
-          rm -rf packages
-          echo "FIRMWARE=$PWD" >> ${{ github.env }}
-          echo "status=success" >> ${{ github.output }}
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Upload firmware directory
-        uses: actions/upload-artifact@v4
-        if: ${{ env.UPLOAD_FIRMWARE }} == 'true' && ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        with:
-          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-          path: ${{ env.FIRMWARE }}
-
-      - name: Generate release tag
-        id: tag
-        if: ${{ env.UPLOAD_RELEASE }} == 'true' && ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        run: |
-          echo "release_tag=${{ env.DEVICE_NAME }}-$(date +"%Y.%m.%d-%H%M")" >> ${{ github.output }}
-          touch release.txt
-          echo "status=success" >> ${{ github.output }}
-
-      - name: Upload firmware to release
-        uses: softprops/action-gh-release@v2
+      - name: Clear server space
+        id: clean
         if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        env:
-          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
+        run: |
+          # Clean up server space
+          cd openwrt/
+          [[ -d "output" ]] || mkdir output
+          cp -f bin/targets/*/*/*rootfs.tar.gz output/
+          cp -f .config output/config
+          rm -rf $(ls . | grep -v "^output$" | xargs) 2>/dev/null
+
+          # Set output information
+          df -hT ${PWD}
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Upload OpenWrt to Release
+        uses: ncipollo/release-action@main
+        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
         with:
-          tag_name: ${{ steps.tag.outputs.release_tag }}
-          body_path: release.txt
-          files: ${{ env.FIRMWARE }}/*
+          tag: ${{ env.build_tag }}
+          artifacts: openwrt/output/*
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          makeLatest: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Packaging OpenWrt
+        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
+        uses: ophub/amlogic-s9xxx-openwrt@main
+        with:
+          openwrt_path: openwrt/output/*rootfs.tar.gz
+          openwrt_ip: ${{ inputs.openwrt_ip || '192.168.7.1' }}
+          openwrt_board: ${{ inputs.openwrt_board || 'r68s' }}
+          openwrt_kernel: ${{ inputs.openwrt_kernel || '5.15.1_6.1.1' }}
+          auto_kernel: ${{ inputs.auto_kernel || true }}
+          kernel_repo: ${{ inputs.kernel_repo || 'ophub/kernel' }}
+          kernel_usage: ${{ inputs.kernel_usage || 'flippy' }}
+          builder_name: ${{ inputs.builder_name || 'plum' }}
+
+      - name: Upload the packaged OpenWrt
+        uses: ncipollo/release-action@main
+        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
+        with:
+          tag: ${{ env.build_tag }}
+          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          makeLatest: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          body: |
+            ### OpenWrt Image information
+            - Default IP: `192.168.7.1`
+            - Default username: `root`
+            - Default password: `password`
+            - Default WIFI name: `OpenWrt`
+            - Default WIFI password: `none`
+            ### Install to EMMC
+            - Login to OpenWrt → `System` → `Amlogic Service` → `Install OpenWrt`
+            ### OpenWrt source code
+            - [${{ env.REPO_NAME }}](${{ env.REPO_URL }}/tree/${{ env.REPO_BRANCH }})
+            ### Applicable platform
+            - 🐧 `arm64`
+            - 🐋 Docker image: https://hub.docker.com/u/ophub
 
       - name: Delete workflow runs
-        uses: Mattraks/delete-workflow-runs@v2
+        uses: Mattraks/delete-workflow-runs@main
         with:
           token: ${{ secrets.RELEASES_TOKEN }}
           retain_days: 0
           keep_minimum_runs: 2
 
       - name: Remove old Releases
-        uses: dev-drprasad/delete-older-releases@v1.1.0
+        uses: dev-drprasad/delete-older-releases@master
         if: ${{ env.UPLOAD_RELEASE }} == 'true' && ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
         with:
           keep_latest: 3
